version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - "renebentes"
    reviewers:
      - "renebentes"
      - "copilot"
    commit-message:
      prefix: "build"
      include: "scope"
