services:
  webapp:
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8081
      - ASPNETCORE_HTTPS_PORTS=8082
      - ASPNETCORE_URLS=http://+:8081
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/dev-certs/https:/home/app/.aspnet/https:ro
      - ${HOME}/.aspnet/dev-certs/https:/root/.aspnet/https:ro
