name: dima

services:
  dima.webapp:
    image: ${DOCKER_REGISTRY-}dimawebapp
    build:
      context: .
      dockerfile: src/Dima.WebApp/Dockerfile

  dima.api:
    image: ${DOCKER_REGISTRY-}dimaapi
    build:
      context: .
      dockerfile: src/Dima.Api/Dockerfile

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=dima
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
